# Site settings
title: Idyll Chow
email: idyllzhou@gmail.com
disqus_shortname: idyllchow
description: "Personal blog about programming..."
baseurl: ""
url: "https://zhoushibo.com"
twitter_username: idyllchow
github_username:  idyllchow
# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

social:
  - title: "github"
    url: "https://github.com/idyllchow"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/idyllchow"
  - title: "youtube"
    url: "https://www.youtube.com/channel/XXXXX"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: "UA-79164781-1"
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    China/GuangZhou
locale:      cn
future:      true
highlighter: rouge
#pygments: true
#gems:
#  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
#gems: [jekyll-paginate]
gems:
  - jekyll-sitemap
  - jekyll-paginate
