# Site settings
title: Idyll Chow
email: idyllzhou@gmail.com
description: "Personal blog about programming, hacking, open-source, startups, git, vim, linux, etc."
baseurl: ""
url: "https://zhoushibo.com"
twitter_username: idyllchow
github_username:  idyllchow

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap

